name: Deploy revised Lambda Function

env:
  ARTIFACT_NAME: csye6225-lambda-${{ github.run_number }}.zip
  AWS_REGION: us-east-1

on:
  push:
    branches: [ main ]

jobs:
  CI_CD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y zip unzip


      - name: Build Deployment Artifact
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} index.js

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy Artifact to S3
        run: |
          aws s3 cp ${{ env.ARTIFACT_NAME }} s3://${{ secrets.CODEDEPLOY_BUCKET }}/${{ env.ARTIFACT_NAME }}

      - name: Call to Lambda to Update
        run: |
          aws lambda update-function-code --function-name lambda_email_updates --region us-east-1 --zip-file fileb://${{ env.ARTIFACT_NAME }}





